### ISSUE TITLE
Linking fails on OS X, because the linkerflag "-fuse-ld=gold" is not supported

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/fsical-management#19]
## Summary

Currently, `-fuse-ld=gold` is added to then linker flags in `dub.json`. This is not supported on OS X, so we should remove it and use commandline switches to choose the gold linker, if we want to. The current state results in the build failing at the linking step on OS X:
```
Linking...
ld: unknown option: -fuse-ld=gold
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: linker exited with status 1
dmd failed with exit code 1.
```

## Steps to reproduce
Run `dub` inside the project's root directory.

## Actual behaviour
Linking fails

## Expected behaviour
Linking succeeds

## Context
- The problem started happening after 011d3c21b6fcd6c4079ade192ce286f2128a49e7 which includes is the addition of the linker flag mentioned before.
- The problem happens on every compilation attempt
## Configuration and environment

 - Version: cc9b452a2f7e18d52527dea3ff0314dca3d3572e
 - OS and version of OS: OS X 10.13.2 (17C205)
 - Architecture: x86_64

## Other things to be mentioned
We should simply remove the flag and choose to opt into gold using commandline flags.

**Comment by pheerai** [comment]
Closed by #24.
