### ISSUE TITLE
Make OpenSSL-1.1 the default when compiling

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/fsical-management#20]
## Summary
The project currently defaults to OpenSSL-1.0. To use 1.1, one needs to use commandline switches on every `dub`command. We should switch those defaults around

## User story
As a developer, I want to use OpenSSL-1.1 without having to use a commandline switch so that I don't have to remember this flag.

## Rationale
All current developers you OpenSSL-1.1, so it is sensible to set it as the default.

## Acceptance criteria
- Set OpenSSl-1.1 as the default in `dub.json`. See http://vibed.org/blog/posts/vibe-release-0.8.2#note-about-openssl-support on how to implement this.

**Comment by pheerai** [comment]
Closed by #25
