### ISSUE TITLE
Automatically generate coverage reports

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/fsical-management#27]
## Summary
We should regularly (triggered by ci-builds) generate coverage reports. The total coverage should be displayed in the `README.md` as a badge.

## User story
As a developer, I want to see the total coverage in the `README.md` so that I have quick access to this information.

## Rationale
Having regular coverage reports will animate the developers to ensure that coverage increases. #1 also states that we are aiming for a coverage of at least 70% and this feature will enable us to see, if we hit or miss that goal.

## Acceptance criteria
- generate coverage reports on every ci-build
- use https://codecov.io to analyze and display the coverage information
- display a badge showing the total coverage in the `README.md`

**Comment by pheerai** [comment]
This is implemented with #28
