### ISSUE TITLE
Use brackets instead of "<" and ">" for placeholders in the issue/pullrequest templates

### ISSUE THREAD

**Issue by ghost91-** [fsimphy/fsical-management#29]
## Summary
Using "<" and ">" results in weird behaviour, because sometimes it gets parsed as an xml tag. So we should use brackets ("[" and "]") instead.

**Comment by pheerai** [comment]
We could even prepare this for usage with the GithubAPI and some modern language, this would imply using "${foo}" as variable specifier.
